/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MnProgressBar {
    'max': number;
    'value': number;
  }
  interface MnProgressBarAttributes extends StencilHTMLAttributes {
    'max'?: number;
    'value'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MnProgressBar': Components.MnProgressBar;
  }

  interface StencilIntrinsicElements {
    'mn-progress-bar': Components.MnProgressBarAttributes;
  }


  interface HTMLMnProgressBarElement extends Components.MnProgressBar, HTMLStencilElement {}
  var HTMLMnProgressBarElement: {
    prototype: HTMLMnProgressBarElement;
    new (): HTMLMnProgressBarElement;
  };

  interface HTMLElementTagNameMap {
    'mn-progress-bar': HTMLMnProgressBarElement
  }

  interface ElementTagNameMap {
    'mn-progress-bar': HTMLMnProgressBarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
